### ISSUE TITLE
机器人配置问题

### ISSUE THREAD

**Issue by 15h6** [fxxk-bot/bfv-bot#1]
### 出现问题的功能

例如

> 找不到机器人配置文件
PS C:\Users\123\Desktop\121> .\windows-x64-bfv-bot
panic: 缺少配置文件路径

goroutine 1 [running]:
bfv-bot/common/initialize.Viper()
        /root/bfv-bot/common/initialize/viper.go:15 +0x1d8
main.main()
        /root/bfv-bot/main.go:17 +0x1f
PS C:\Users\123\Desktop\121> ./windows-x64-bfv-bot
panic: 缺少配置文件路径

goroutine 1 [running]:
bfv-bot/common/initialize.Viper()
        /root/bfv-bot/common/initialize/viper.go:15 +0x1d8
main.main()
        /root/bfv-bot/main.go:17 +0x1f

**Comment by 15h6** [comment]
您好！使用你配置里的http运行失败
{"error": "Post \"http://192.168.93.130:3001/send_private_msg_async\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}

**Comment by 15h6** [comment]
佬！机器人查询是成功的 但是创建文件夹失败 文件异常
2024/10/09 - 18:45:05.286       [35mDEBUG[0m  utils/http.go:115       Get     {"url": "https://api.bfvrobot.net/api/v2/player/getCommunityStatus", "stringResult": "{\"success\":1,\"data\":{\"personaId\":\"1007011790313\",\"operationStatus\":-1,\"operationStatusName\":\"无状态\",\"reasonStatus\":0,\"reasonStatusName\":\"数据正常\"}}"}
2024/10/09 - 18:45:06.074       [35mDEBUG[0m  utils/http.go:115       Get     {"url": "https://api.bfban.com/api/player", "stringResult": "{\"error\":1,\"code\":\"player.notFound\"}"}
2024/10/09 - 18:45:06.075       [31mERROR[0m  utils/bfv.go:49 创建文件夹失败  {"error": "mkdir /bfv-bot/test/20241009/: The system cannot find the path specified."}
2024/10/09 - 18:45:06.083       [31mERROR[0m  api/event.go:549        path, err := utils.QueryAndStore(value) {"name": "DicedOrange", "error": "服务器文件异常"}
2024/10/09 - 18:45:06.084       [34mINFO[0m   initialize/gin.go:60    [GIN] |[0;42m 200 [0m|   2667ms |        127.0.0.1 |[0;48;2;120;220;232;38;2;255;255;255m POST    [0m "/api/event/post"

**Comment by 15h6** [comment]
2024/10/09 - 18:46:42.837       [31mERROR[0m  api/event.go:574        third.GetBanLogByName   {"name": "DicedOrange", "error": "网络异常"}
2024/10/09 - 18:46:42.838       [34mINFO[0m   initialize/gin.go:60    [GIN] |[0;42m 200 [0m|   5002ms |        127.0.0.1 |[0;48;2;120;220;232;38;2;255;255;255m POST    [0m "/api/event/post"

**Comment by 15h6** [comment]
cx查询功能    输入cx  应该结果战绩图    实际结果：查询失败: 服务器文件异常
2024/10/09 - 19:09:17.772       [35mDEBUG[0m  utils/http.go:115       Get     {"url": "https://api.bfvrobot.net/api/v2/bfv/checkPlayer", "stringResult": "{\"status\":1,\"message\":\"successful\",\"data\":{\"userId\":1015099790313,\"name\":\"dicedorange\",\"personaId\":1007011790313}}"}
2024/10/09 - 19:09:18.225       [35mDEBUG[0m  utils/http.go:115       Get     {"url": "https://api.bfvrobot.net/api/worker/player/getAllStats", "stringResult": "{\"success\":1,\"code\":\"playerAll.success\",\"data\":{\"weapons\":[{\"name\":\"斯登冲锋枪\",\"damage\":182,\"shotsHit\":6,\"timeEquipped\":2095,\"shotsFired\":168,\"kills\":1,\"score\":2564,\"killsPerMinute\":\"0.03\",\"accuracy\":\"3.57%\",\"headshots\":\"0%\",\"hitVKills\":\"6.00\",\"damagePerHit\":\"30.33\",\"damagePerMinute\":\"5.21\"},{\"name\":\"索米 KP/-31 冲锋枪\",\"damage\":26169,\"shotsHit\":864,\"headshotKills\":25,\"timeEquipped\":16210,\"shotsFired\":7563,\"kills\":153,\"score\":57238,\"killsPerMinute\":\"0.57\",\"accuracy\":\"11.42%\",\"headshots\":\"16.34%\",\"hitVKills\":\"5.65\",\"damagePerHit\":\"30.29\",\"damagePerMinute\":\"96.86\"},{\"name\":\"M3 冲锋枪\",\"damage\":2067,\"shotsHit\":51,\"headshotKills\":2,\"timeEquipped\":3560,\"shotsFired\":440,\"kills\":9,\"score\":6811,\"killsPerMinute\":\"0.15\",\"accuracy\":\"11.59%\",\"headshots\":\"22.22%\",\"hitVKills\":\"5.67\",\"damagePerHit\":\"40.53\",\"damagePerMinute\":\"34.84\"},{\"name\":\"二式冲锋枪\",\"damage\":374,\"shotsHit\":11,\"headshotKills\":1,\"timeEquipped\":205,\"shotsFired\":128,\"kills\":1,\"score\":464,\"killsPerMinute\":\"0.29\",\"accuracy\":\"8.59%\",\"headshots\":\"100.00%\",\"hitVKills\":\"11.00\",\"damagePerHit\":\"34.00\",\"damagePerMinute\":\"109.46\"},{\"name\":\"麦德森机枪\",\"damage\":42698,\"shotsHit\":1286,\"headshotKills\":38,\"timeEquipped\":41055,\"shotsFired\":19516,\"kills\":178,\"score\":109533,\"killsPerMinute\":\"0.26\",\"accuracy\":\"6.59%\",\"headshots\":\"21.35%\",\"hitVKills\":\"7.22\",\"damagePerHit\":\"33.20\",\"damagePerMinute\":\"62.40\"},{\"name\":\"KE7 机枪\",\"damage\":255,\"shotsHit\":11,\"timeEquipped\":410,\"shotsFired\":71,\"kills\":2,\"score\":2091,\"killsPerMinute\":\"0.29\",\"accuracy\":\"15.49%\",\"headshots\":\"0%\",\"hitVKills\":\"5.50\",\"damagePerHit\":\"23.18\",\"damagePerMinute\":\"37.32\"},{\"name\":\"M1A1 卡宾枪\",\"damage\":3551,\"shotsHit\":95,\"headshotKills\":6,\"timeEquipped\":3985,\"shotsFired\":651,\"kills\":24,\"score\":9830,\"killsPerMinute\":\"0.36\",\"accuracy\":\"14.59%\",\"headshots\":\"25.00%\",\"hitVKills\":\"3.96\",\"damagePerHit\":\"37.38\",\"damagePerMinute\":\"53.47\"},{\"name\":\"格韦尔 43 步枪\",\"damage\":5739,\"shotsHit\":116,\"headshotKills\":9,\"timeEquipped\":8995,\"shotsFired\":824,\"kills\":34,\"score\":15937,\"killsPerMinute\":\"0.23\",\"accuracy\":\"14.08%\",\"headshots\":\"26.47%\",\"hitVKills\":\"3.41\",\"damagePerHit\":\"49.47\",\"damagePerMinute\":\"38.28\"},{\"name\":\"M1 加兰德步枪\",\"damage\":11291,\"shotsHit\":242,\"headshotKills\":14,\"timeEquipped\":9005,\"shotsFired\":1648,\"kills\":65,\"score\":27551,\"killsPerMinute\":\"0.43\",\"accuracy\":\"14.68%\",\"headshots\":\"21.54%\",\"hitVKills\":\"3.72\",\"damagePerHit\":\"46.66\",\"damagePerMinute\":\"75.23\"},{\"name\":\"格韦尔 1-5 突击步枪\",\"damage\":165,\"shotsHit\":7,\"timeEquipped\":360,\"shotsFired\":98,\"kills\":1,\"score\":990,\"killsPerMinute\":\"0.17\",\"accuracy\":\"7.14%\",\"headshots\":\"0%\",\"hitVKills\":\"7.00\",\"damagePerHit\":\"23.57\",\"damagePerMinute\":\"27.50\"},{\"name\":\"StG 44 突击步枪\",\"damage\":2126,\"shotsHit\":100,\"headshotKills\":3,\"timeEquipped\":1160,\"shotsFired\":700,\"kills\":13,\"score\":5561,\"killsPerMinute\":\"0.67\",\"accuracy\":\"14.29%\",\"headshots\":\"23.08%\",\"hitVKills\":\"7.69\",\"damagePerHit\":\"21.26\",\"damagePerMinute\":\"109.97\"},{\"name\":\"毛瑟 Kar98k 步枪\",\"damage\":69,\"shotsHit\":1,\"headshotKills\":1,\"timeEquipped\":70,\"shotsFired\":7,\"kills\":1,\"score\":274,\"killsPerMinute\":\"0.86\",\"accuracy\":\"14.29%\",\"headshots\":\"100.00%\",\"hitVKills\":\"1.00\",\"damagePerHit\":\"69.00\",\"damagePerMinute\":\"59.14\"},{\"name\":\"39 反坦克步枪\",\"damage\":1783,\"shotsHit\":14,\"headshotKills\":1,\"timeEquipped\":4875,\"shotsFired\":208,\"kills\":10,\"score\":9380,\"killsPerMinute\":\"0.12\",\"accuracy\":\"6.73%\",\"headshots\":\"10.00%\",\"hitVKills\":\"1.40\",\"damagePerHit\":\"127.36\",\"damagePerMinute\":\"21.94\"},{\"name\":\"斯太尔 M1912 手枪\",\"shotsHit\":3,\"headshotKills\":1,\"timeEquipped\":1930,\"shotsFired\":282,\"kills\":1,\"score\":1485,\"killsPerMinute\":\"0.03\",\"accuracy\":\"1.06%\",\"headshots\":\"100.00%\",\"hitVKills\":\"3.00\"},{\"name\":\"P38 手枪\",\"shotsHit\":8,\"timeEquipped\":70,\"shotsFired\":43,\"kills\":1,\"score\":726,\"killsPerMinute\":\"0.86\",\"accuracy\":\"18.60%\",\"headshots\":\"0%\",\"hitVKills\":\"8.00\"},{\"name\":\"红宝石半自动手枪\",\"shotsHit\":16,\"timeEquipped\":830,\"shotsFired\":327,\"kills\":6,\"score\":2029,\"killsPerMinute\":\"0.43\",\"accuracy\":\"4.89%\",\"headshots\":\"0%\",\"hitVKills\":\"2.67\"},{\"name\":\"区域火炮\",\"shotsHit\":33,\"kills\":4,\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"8.25\"},{\"name\":\"JB-2 火箭弹\",\"shotsHit\":2,\"kills\":1,\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"2.00\"},{\"name\":\"侦 察兵小刀 M1916\",\"shotsHit\":9,\"timeEquipped\":20,\"shotsFired\":15,\"kills\":5,\"score\":735,\"killsPerMinute\":\"15.00\",\"accuracy\":\"60.00%\",\"headshots\":\"0%\",\"hitVKills\":\"1.80\"},{\"name\":\"英军小刀\",\"shotsHit\":27,\"timeEquipped\":305,\"shotsFired\":161,\"kills\":15,\"score\":2958,\"killsPerMinute\":\"2.95\",\"accuracy\":\"16.77%\",\"headshots\":\"0%\",\"hitVKills\":\"1.80\"},{\"name\":\"德国海军匕首\",\"shotsHit\":9,\"timeEquipped\":60,\"shotsFired\":43,\"kills\":7,\"score\":1187,\"killsPerMinute\":\"7.00\",\"accuracy\":\"20.93%\",\"headshots\":\"0%\",\"hitVKills\":\"1.29\"},{\"name\":\"匕首\",\"shotsHit\":2,\"timeEquipped\":30,\"shotsFired\":33,\"kills\":2,\"score\":280,\"killsPerMinute\":\"4.00\",\"accuracy\":\"6.06%\",\"headshots\":\"0%\",\"hitVKills\":\"1.00\"},{\"name\":\"武士刀\",\"shotsHit\":14,\"timeEquipped\":660,\"shotsFired\":724,\"kills\":10,\"score\":4172,\"killsPerMinute\":\"0.91\",\"accuracy\":\"1.93%\",\"headshots\":\"0%\",\"hitVKills\":\"1.40\"},{\"name\":\"狮头剑\",\"shotsHit\":44,\"timeEquipped\":300,\"shotsFired\":152,\"kills\":20,\"score\":4144,\"killsPerMinute\":\"4.00\",\"accuracy\":\"28.95%\",\"headshots\":\"0%\",\"hitVKills\":\"2.20\"},{\"name\":\"棍棒\",\"shotsHit\":2,\"timeEquipped\":160,\"shotsFired\":25,\"kills\":2,\"score\":259,\"killsPerMinute\":\"0.75\",\"accuracy\":\"8.00%\",\"headshots\":\"0%\",\"hitVKills\":\"1.00\"},{\"name\":\"铁铲\",\"shotsHit\":1,\"timeEquipped\":5,\"shotsFired\":7,\"kills\":1,\"score\":240,\"killsPerMinute\":\"12.00\",\"accuracy\":\"14.29%\",\"headshots\":\"0%\",\"hitVKills\":\"1.00\"},{\"name\":\"逃生斧\",\"shotsHit\":7,\"timeEquipped\":40,\"shotsFired\":30,\"kills\":3,\"score\":623,\"killsPerMinute\":\"4.50\",\"accuracy\":\"23.33%\",\"headshots\":\"0%\",\"hitVKills\":\"2.33\"}],\"vehicles\":[{\"name\":\"谢尔曼坦克\",\"damage\":8825,\"timeEquipped\":3430,\"kills\":24,\"destroy\":16,\"destroyed\":3,\"killsPerMinute\":\"0.42\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\",\"damagePerHit\":\"0.00\",\"damagePerMinute\":\"154.37\"},{\"name\":\"八八式高射炮\",\"timeEquipped\":640,\"kills\":17,\"killsPerMinute\":\"1.59\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"九七式\",\"damage\":2029,\"timeEquipped\":965,\"kills\":3,\"destroy\":3,\"destroyed\":2,\"killsPerMinute\":\"0.19\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\",\"damagePerHit\":\"0.00\",\"damagePerMinute\":\"126.16\"},{\"name\":\"LVT\",\"damage\":18648,\"timeEquipped\":6395,\"kills\":55,\"destroy\":4,\"destroyed\":4,\"killsPerMinute\":\"0.52\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\",\"damagePerHit\":\"0.00\",\"damagePerMinute\":\"174.96\"},{\"name\":\"LCVP\",\"timeEquipped\":1075,\"kills\":2,\"destroy\":1,\"killsPerMinute\":\"0.11\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"6 磅炮\",\"timeEquipped\":630,\"kills\":4,\"destroy\":1,\"killsPerMinute\":\"0.38\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"40 毫米防空炮\",\"timeEquipped\":3395,\"kills\":24,\"destroyed\":15,\"killsPerMinute\":\"0.42\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"10 式\",\"timeEquipped\":455,\"kills\":9,\"destroy\":1,\"killsPerMinute\":\"1.19\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"}],\"gadgets\":[{\"name\":\"刺雷\",\"timeEquipped\":2910,\"kills\":23,\"killsPerMinute\":\"0.47\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"战斗信号枪\",\"timeEquipped\":85,\"kills\":1,\"killsPerMinute\":\"0.71\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"反坦克火箭筒\",\"timeEquipped\":290,\"kills\":2,\"killsPerMinute\":\"0.41\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"PIAT榴弹发射器\",\"timeEquipped\":1890,\"kills\":13,\"killsPerMinute\":\"0.41\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"防空铁拳\",\"timeEquipped\":2130,\"kills\":7,\"killsPerMinute\":\"0.20\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"M2 火焰喷射器\",\"timeEquipped\":695,\"kills\":5,\"killsPerMinute\":\"0.43\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"反坦克捆绑式手雷\",\"timeEquipped\":40,\"kills\":2,\"killsPerMinute\":\"3.00\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"黏性手雷\",\"timeEquipped\":40,\"kills\":3,\"killsPerMinute\":\"4.50\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"}],\"unpackWeapon\":[],\"personaId\":1007011790313,\"kills\":766,\"deaths\":1456,\"killAssists\":221,\"heals\":5813,\"revives\":296,\"headshots\":106,\"rank\":27,\"wins\":21,\"roundsPlayed\":63,\"loses\":37,\"highestKillStreak\":15,\"awardScore\":218000,\"bonusScore\":89227,\"squadScore\":110507,\"totalScore\":394237,\"killDeath\":\"0.53\",\"timePlayed\":129300,\"killsPerMinute\":\"0.36\",\"winPercent\":\"33.33%\",\"scorePerMinute\":182.94}}"}
2024/10/09 - 19:09:18.593       [35mDEBUG[0m  utils/http.go:115       Get     {"url": "https://api.bfvrobot.net/api/v2/player/getCommunityStatus", "stringResult": "{\"success\":1,\"data\":{\"personaId\":\"1007011790313\",\"operationStatus\":-1,\"operationStatusName\":\"无状态\",\"reasonStatus\":0,\"reasonStatusName\":\"数据正常\"}}"}
2024/10/09 - 19:09:19.276       [35mDEBUG[0m  utils/http.go:115       Get     {"url": "https://api.bfban.com/api/player", "stringResult": "{\"error\":1,\"code\":\"player.notFound\"}"}
2024/10/09 - 19:09:19.276       [31mERROR[0m  utils/bfv.go:49 创建文件夹失败  {"error": "mkdir /bfv-bot/test/20241009/: The system cannot find the path specified."}
2024/10/09 - 19:09:19.279       [31mERROR[0m  api/event.go:549        path, err := utils.QueryAndStore(value) {"name": "DicedOrange", "error": "服务器文件异常"}
2024/10/09 - 19:09:19.288       [34mINFO[0m   initialize/gin.go:60    [GIN] |[0;42m 200 [0m|   2097ms |        127.0.0.1 |[0;48;2;120;220;232;38;2;255;255;255m POST    [0m "/api/event/post"

**Comment by 15h6** [comment]
佬  banlog查询成功 但是不输出
2024/10/10 - 14:27:30.165       [31mERROR[0m  initialize/gin.go:123   [Recovery from panic]   {"error": "time: missing Location in call to Time.In", "request": "POST /api/event/post HTTP/1.1 Host: 127.0.0.1:19997 Accept: */* Accept-Encoding: gzip, deflate Accept-Language: * Connection: keep-alive Content-Length: 421 Content-Type: application/json Sec-Fetch-Mode: cors User-Agent: node X-Self-Id: 3996023151  "}
2024/10/10 - 14:27:30.171       [31mERROR[0m  initialize/gin.go:133   goroutine 43 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
bfv-bot/common/initialize.Routers.GinRecovery.func2.1()
        /root/bfv-bot/common/initialize/gin.go:132 +0x3c9
panic({0x1799700?, 0x1a2d210?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
time.Time.In(...)
        /usr/local/go/src/time/time.go:1167
bfv-bot/common/utils.Format({0xc00043a9c0?, 0xc000067008?, 0x0?})
        /root/bfv-bot/common/utils/datetime.go:29 +0xde
bfv-bot/common/utils.GetBanLog({0xc00043e2a7?, 0xc00031a040?})
        /root/bfv-bot/common/utils/third.go:142 +0x3d0
bfv-bot/api.banlog(0x17d2de0?, 0xc0002ac100, {0xc00043e2a0?, 0x11?})
        /root/bfv-bot/api/event.go:572 +0x65
bfv-bot/api.(*EventApi).Post(0x18d6bdc?, 0xc0002ac100)
        /root/bfv-bot/api/event.go:109 +0x9a9
github.com/gin-gonic/gin.(*Context).Next(0xc0002ac100)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 +0x2b
bfv-bot/common/initialize.Routers.Options.func3(0xc0002ac100)
        /root/bfv-bot/common/utils/gin.go:17 +0xb3
github.com/gin-gonic/gin.(*Context).Next(0xc0002ac100)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 +0x2b
bfv-bot/common/initialize.Routers.GinRecovery.func2(0xc000047840?)
        /root/bfv-bot/common/initialize/gin.go:139 +0x52
github.com/gin-gonic/gin.(*Context).Next(0xc0002ac100)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 +0x2b
bfv-bot/common/initialize.Routers.GinLogger.func1(0xc0002ac100)
        /root/bfv-bot/common/initialize/gin.go:52 +0x225
github.com/gin-gonic/gin.(*Context).Next(...)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00006eea0, 0xc0002ac100)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:489 +0x650
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00006eea0, {0x1a35da0, 0xc0002141c0}, 0xc0000c3680)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:445 +0x198
net/http.serverHandler.ServeHTTP({0x1a33b28?}, {0x1a35da0?, 0xc0002141c0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc0001e2990, {0x1a37148, 0xc00014cc30})
        /usr/local/go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3285 +0x4b4

**Comment by 15h6** [comment]
可以知道大佬你是哪个群组的吗

**Comment by 15h6** [comment]
佬 可以把机器人已修改群昵称精简到加群基础数据里吗 这样进群通知也简洁一点
