### ISSUE TITLE
cx功能不能用

### ISSUE THREAD

**Issue by WONGIII** [fxxk-bot/bfv-bot#10]
### 出现问题的功能

例如

> 查询功能, cx=xxxx, 失败

2024/10/13 - 23:09:40.577       INFO    initialize/gin.go:60    [GIN] | 200 |      0ms |        127.0.0.1 | POST     "/api/event/post"
2024/10/13 - 23:11:15.748       DEBUG   initialize/gin.go:44    msg: {"self_id":3771200484,"user_id":3502207963,"time":1728832308,"message_id":1163651693,"message_seq":1163651693,"real_id":1163651693,"message_type":"group","sender":{"user_id":3502207963,"nickname":"💫王iii","card":"","role":"owner"},"raw_message":"cx","font":14,"sub_type":"normal","message":[{"type":"text","data":{"text":"cx"}}],"message_format":"array","post_type":"message","group_id":768550416}

2024/10/13 - 23:11:16.442       DEBUG   utils/http.go:115       Get     {"url": "https://api.bfvrobot.net/api/v2/bfv/checkPlayer", "stringResult": "{\"status\":1,\"message\":\"successful\",\"data\":{\"userId\":1011388878455,\"name\":\"WONG1I1\",\"personaId\":1005419078455}}"}
2024/10/13 - 23:11:17.666       DEBUG   utils/http.go:115       Get     {"url": "https://api.bfvrobot.net/api/worker/player/getAllStats", "stringResult": "{\"success\":1,\"code\":\"playerAll.success\",\"data\":{\"weapons\":[{\"name\":\"MP40 冲锋枪\",\"damage\":285,\"shotsHit\":8,\"timeEquipped\":105,\"shotsFired\":71,\"kills\":2,\"score\":335,\"killsPerMinute\":\"1.14\",\"accuracy\":\"11.27%\",\"headshots\":\"0%\",\"hitVKills\":\"4.00\",\"damagePerHit\":\"35.63\",\"damagePerMinute\":\"162.86\"},{\"name\":\"MP28 冲锋枪\",\"damage\":15894,\"shotsHit\":441,\"headshotKills\":14,\"timeEquipped\":9130,\"shotsFired\":5293,\"kills\":83,\"score\":28146,\"killsPerMinute\":\"0.55\",\"accuracy\":\"8.33%\",\"headshots\":\"16.87%\",\"hitVKills\":\"5.31\",\"damagePerHit\":\"36.04\",\"damagePerMinute\":\"104.45\"},{\"name\":\"斯登冲锋枪\",\"damage\":222,\"shotsHit\":9,\"timeEquipped\":810,\"shotsFired\":166,\"kills\":2,\"score\":502,\"killsPerMinute\":\"0.15\",\"accuracy\":\"5.42%\",\"headshots\":\"0%\",\"hitVKills\":\"4.50\",\"damagePerHit\":\"24.67\",\"damagePerMinute\":\"16.44\"},{\"name\":\"索米 KP/-31 冲锋枪\",\"damage\":451631,\"shotsHit\":12708,\"headshotKills\":391,\"timeEquipped\":163350,\"shotsFired\":105408,\"kills\":2463,\"score\":716323,\"killsPerMinute\":\"0.90\",\"accuracy\":\"12.06%\",\"headshots\":\"15.87%\",\"hitVKills\":\"5.16\",\"damagePerHit\":\"35.54\",\"damagePerMinute\":\"165.89\"},{\"name\":\"ZK-383 冲锋枪\",\"damage\":192693,\"shotsHit\":5425,\"headshotKills\":174,\"timeEquipped\":58735,\"shotsFired\":39526,\"kills\":1054,\"score\":289441,\"killsPerMinute\":\"1.08\",\"accuracy\":\"13.73%\",\"headshots\":\"16.51%\",\"hitVKills\":\"5.15\",\"damagePerHit\":\"35.52\",\"damagePerMinute\":\"196.84\"},{\"name\":\"百式冲锋枪\",\"damage\":4580,\"shotsHit\":139,\"headshotKills\":5,\"timeEquipped\":10115,\"shotsFired\":1465,\"kills\":19,\"score\":29260,\"killsPerMinute\":\"0.11\",\"accuracy\":\"9.49%\",\"headshots\":\"26.32%\",\"hitVKills\":\"7.32\",\"damagePerHit\":\"32.95\",\"damagePerMinute\":\"27.17\"},{\"name\":\"刘易斯机枪\",\"damage\":65,\"shotsHit\":2,\"timeEquipped\":25,\"shotsFired\":26,\"kills\":1,\"score\":164,\"killsPerMinute\":\"2.40\",\"accuracy\":\"7.69%\",\"headshots\":\"0%\",\"hitVKills\":\"2.00\",\"damagePerHit\":\"32.50\",\"damagePerMinute\":\"156.00\"},{\"name\":\"麦德森机枪\",\"damage\":164063,\"shotsHit\":5094,\"headshotKills\":165,\"timeEquipped\":70690,\"shotsFired\":38360,\"kills\":810,\"score\":308202,\"killsPerMinute\":\"0.69\",\"accuracy\":\"13.28%\",\"headshots\":\"20.37%\",\"hitVKills\":\"6.29\",\"damagePerHit\":\"32.21\",\"damagePerMinute\":\"139.25\"},{\"name\":\"KE7 机枪\",\"damage\":361,\"shotsHit\":9,\"timeEquipped\":315,\"shotsFired\":79,\"kills\":1,\"score\":501,\"killsPerMinute\":\"0.19\",\"accuracy\":\"11.39%\",\"headshots\":\"0%\",\"hitVKills\":\"9.00\",\"damagePerHit\":\"40.11\",\"damagePerMinute\":\"68.76\"},{\"name\":\"格韦尔 1-5 突击步枪\",\"damage\":6793,\"shotsHit\":164,\"headshotKills\":5,\"timeEquipped\":3775,\"shotsFired\":1087,\"kills\":29,\"score\":11683,\"killsPerMinute\":\"0.46\",\"accuracy\":\"15.09%\",\"headshots\":\"17.24%\",\"hitVKills\":\"5.66\",\"damagePerHit\":\"41.42\",\"damagePerMinute\":\"107.97\"},{\"name\":\"StG 44 突击步枪\",\"damage\":20398,\"shotsHit\":643,\"headshotKills\":25,\"timeEquipped\":8805,\"shotsFired\":5337,\"kills\":114,\"score\":37153,\"killsPerMinute\":\"0.78\",\"accuracy\":\"12.05%\",\"headshots\":\"21.93%\",\"hitVKills\":\"5.64\",\"damagePerHit\":\"31.72\",\"damagePerMinute\":\"139.00\"},{\"name\":\"温彻斯特 1907 型半自动步枪\",\"damage\":679,\"shotsHit\":29,\"timeEquipped\":655,\"shotsFired\":219,\"kills\":4,\"score\":1099,\"killsPerMinute\":\"0.37\",\"accuracy\":\"13.24%\",\"headshots\":\"0%\",\"hitVKills\":\"7.25\",\"damagePerHit\":\"23.41\",\"damagePerMinute\":\"62.20\"},{\"name\":\"M2 卡宾枪\",\"damage\":15117,\"shotsHit\":340,\"headshotKills\":12,\"timeEquipped\":4555,\"shotsFired\":2803,\"kills\":81,\"score\":21280,\"killsPerMinute\":\"1.07\",\"accuracy\":\"12.13%\",\"headshots\":\"14.81%\",\"hitVKills\":\"4.20\",\"damagePerHit\":\"44.46\",\"damagePerMinute\":\"199.13\"},{\"name\":\"李-恩菲尔德 No.4 Mk I 步枪\",\"damage\":3060,\"shotsHit\":56,\"headshotKills\":3,\"timeEquipped\":2860,\"shotsFired\":205,\"kills\":8,\"score\":8585,\"killsPerMinute\":\"0.17\",\"accuracy\":\"27.32%\",\"headshots\":\"37.50%\",\"hitVKills\":\"7.00\",\"damagePerHit\":\"54.64\",\"damagePerMinute\":\"64.20\"},{\"name\":\"M28 步 枪榴弹发射器\",\"damage\":231,\"shotsHit\":2,\"timeEquipped\":40,\"shotsFired\":4,\"kills\":1,\"score\":241,\"killsPerMinute\":\"1.50\",\"accuracy\":\"50.00%\",\"headshots\":\"0%\",\"hitVKills\":\"2.00\",\"damagePerHit\":\"115.50\",\"damagePerMinute\":\"346.50\"},{\"name\":\"P38 手枪\",\"shotsHit\":58,\"headshotKills\":2,\"timeEquipped\":3465,\"shotsFired\":357,\"kills\":19,\"score\":9270,\"killsPerMinute\":\"0.33\",\"accuracy\":\"16.25%\",\"headshots\":\"10.53%\",\"hitVKills\":\"3.05\"},{\"name\":\"M27 左轮手枪\",\"shotsHit\":21,\"headshotKills\":5,\"timeEquipped\":945,\"shotsFired\":68,\"kills\":12,\"score\":2806,\"killsPerMinute\":\"0.76\",\"accuracy\":\"30.88%\",\"headshots\":\"41.67%\",\"hitVKills\":\"1.75\"},{\"name\":\"M1911 手枪（消音消焰）\",\"shotsHit\":26,\"timeEquipped\":1875,\"shotsFired\":191,\"kills\":6,\"score\":1884,\"killsPerMinute\":\"0.19\",\"accuracy\":\"13.61%\",\"headshots\":\"0%\",\"hitVKills\":\"4.33\"},{\"name\":\"区域火炮\",\"shotsHit\":58,\"kills\":5,\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"11.60\"},{\"name\":\"侦 察兵小刀 M1916\",\"shotsHit\":3,\"timeEquipped\":5,\"shotsFired\":16,\"kills\":2,\"score\":376,\"killsPerMinute\":\"24.00\",\"accuracy\":\"18.75%\",\"headshots\":\"0%\",\"hitVKills\":\"1.50\"},{\"name\":\"廓尔喀弯刀\",\"shotsHit\":728,\"headshotKills\":23,\"timeEquipped\":2300,\"shotsFired\":1594,\"kills\":581,\"score\":119143,\"killsPerMinute\":\"15.16\",\"accuracy\":\"45.67%\",\"headshots\":\"3.96%\",\"hitVKills\":\"1.25\"},{\"name\":\"英军小刀\",\"shotsHit\":127,\"timeEquipped\":2580,\"shotsFired\":641,\"kills\":79,\"score\":17637,\"killsPerMinute\":\"1.84\",\"accuracy\":\"19.81%\",\"headshots\":\"0%\",\"hitVKills\":\"1.61\"},{\"name\":\"尖嘴镐\",\"shotsHit\":44,\"timeEquipped\":670,\"shotsFired\":115,\"kills\":17,\"score\":4706,\"killsPerMinute\":\"1.52\",\"accuracy\":\"38.26%\",\"headshots\":\"0%\",\"hitVKills\":\"2.59\"}],\"vehicles\":[{\"name\":\"M3 冲锋车\",\"timeEquipped\":240,\"kills\":9,\"killsPerMinute\":\"2.25\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"T48 GMC\",\"timeEquipped\":85,\"kills\":3,\"killsPerMinute\":\"2.12\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"九五式小型乘用车\",\"timeEquipped\":540,\"kills\":1,\"destroy\":2,\"destroyed\":1,\"killsPerMinute\":\"0.11\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"GPW\",\"timeEquipped\":1870,\"kills\":3,\"destroy\":1,\"killsPerMinute\":\"0.10\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"丘吉尔 MK VII 坦克\",\"damage\":832,\"timeEquipped\":95,\"kills\":6,\"killsPerMinute\":\"3.79\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\",\"damagePerHit\":\"0.00\",\"damagePerMinute\":\"525.47\"},{\"name\":\"丘吉尔鳄鱼坦克\",\"timeEquipped\":480,\"kills\":5,\"killsPerMinute\":\"0.63\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"虎 I 坦克\",\"damage\":3739,\"timeEquipped\":1265,\"kills\":2,\"destroy\":1,\"destroyed\":1,\"killsPerMinute\":\"0.09\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\",\"damagePerHit\":\"0.00\",\"damagePerMinute\":\"177.34\"},{\"name\":\"谢尔曼坦克\",\"damage\":15853,\"timeEquipped\":5960,\"kills\":50,\"destroy\":4,\"destroyed\":4,\"killsPerMinute\":\"0.50\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\",\"damagePerHit\":\"0.00\",\"damagePerMinute\":\"159.59\"},{\"name\":\"T34卡利欧波\",\"timeEquipped\":785,\"kills\":6,\"killsPerMinute\":\"0.46\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"八八式高射炮\",\"timeEquipped\":655,\"kills\":3,\"killsPerMinute\":\"0.27\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"九七式\",\"damage\":21246,\"timeEquipped\":5050,\"kills\":72,\"destroy\":8,\"destroyed\":1,\"killsPerMinute\":\"0.86\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\",\"damagePerHit\":\"0.00\",\"damagePerMinute\":\"252.43\"},{\"name\":\"LVT\",\"damage\":26747,\"timeEquipped\":6955,\"kills\":51,\"destroy\":1,\"killsPerMinute\":\"0.44\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\",\"damagePerHit\":\"0.00\",\"damagePerMinute\":\"230.74\"},{\"name\":\"特二式内火艇\",\"damage\":130,\"timeEquipped\":60,\"kills\":1,\"killsPerMinute\":\"1.00\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\",\"damagePerHit\":\"0.00\",\"damagePerMinute\":\"130.00\"},{\"name\":\"M8 灰狗\",\"damage\":4497,\"timeEquipped\":1590,\"kills\":3,\"killsPerMinute\":\"0.11\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\",\"damagePerHit\":\"0.00\",\"damagePerMinute\":\"169.70\"},{\"name\":\"小艇\",\"timeEquipped\":165,\"kills\":1,\"killsPerMinute\":\"0.36\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"6 磅炮\",\"timeEquipped\":495,\"kills\":2,\"killsPerMinute\":\"0.24\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"38 型高射炮\",\"timeEquipped\":620,\"kills\":3,\"destroyed\":3,\"killsPerMinute\":\"0.29\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"维克斯机枪\",\"timeEquipped\":345,\"kills\":2,\"killsPerMinute\":\"0.35\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"MG34 定点机枪\",\"timeEquipped\":555,\"kills\":11,\"killsPerMinute\":\"1.19\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"M2 重机枪\",\"timeEquipped\":10,\"kills\":1,\"killsPerMinute\":\"6.00\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"九三式重机枪\",\"timeEquipped\":110,\"kills\":8,\"killsPerMinute\":\"4.36\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"40 毫米防空炮\",\"timeEquipped\":475,\"kills\":4,\"destroyed\":4,\"killsPerMinute\":\"0.51\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"10 式\",\"timeEquipped\":380,\"kills\":1,\"destroy\":1,\"destroyed\":1,\"killsPerMinute\":\"0.16\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"}],\"gadgets\":[{\"name\":\"黏性炸药\",\"timeEquipped\":425,\"kills\":1,\"killsPerMinute\":\"0.14\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"刺雷\",\"timeEquipped\":5190,\"kills\":45,\"killsPerMinute\":\"0.52\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"烟 雾弹步枪\",\"timeEquipped\":14875,\"kills\":1,\"killsPerMinute\":\"0.00\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"反坦克火箭筒\",\"timeEquipped\":895,\"kills\":2,\"killsPerMinute\":\"0.13\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"M1A1 火箭筒\",\"timeEquipped\":145,\"kills\":1,\"killsPerMinute\":\"0.41\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"破片手雷\",\"timeEquipped\":110,\"kills\":14,\"killsPerMinute\":\"7.64\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"燃烧手雷\",\"timeEquipped\":515,\"kills\":15,\"killsPerMinute\":\"1.75\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"爆破手雷\",\"timeEquipped\":25,\"kills\":2,\"killsPerMinute\":\"4.80\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"},{\"name\":\"飞刀\",\"timeEquipped\":25,\"kills\":8,\"killsPerMinute\":\"19.20\",\"accuracy\":\"0%\",\"headshots\":\"0%\",\"hitVKills\":\"0.00\"}],\"unpackWeapon\":[],\"personaId\":1005419078455,\"kills\":5737,\"deaths\":4831,\"killAssists\":1385,\"heals\":23407,\"revives\":1991,\"headshots\":843,\"rank\":71,\"wins\":76,\"roundsPlayed\":182,\"loses\":90,\"highestKillStreak\":16,\"awardScore\":683000,\"bonusScore\":233439,\"squadScore\":407982,\"totalScore\":2009372,\"killDeath\":\"1.19\",\"timePlayed\":408060,\"killsPerMinute\":\"0.84\",\"winPercent\":\"41.76%\",\"scorePerMinute\":293.35}}"}
2024/10/13 - 23:11:17.866       DEBUG   utils/http.go:115       Get     {"url": "https://api.bfvrobot.net/api/v2/player/getCommunityStatus", "stringResult": "{\"success\":1,\"data\":{\"personaId\":1005419078455,\"operationStatus\":-1,\"operationStatusName\":\"无状态\",\"reasonStatus\":0,\"reasonStatusName\":\"数据正常\"}}"}
2024/10/13 - 23:11:18.477       DEBUG   utils/http.go:115       Get     {"url": "https://api.bfban.com/api/player", "stringResult": "{\"error\":1,\"code\":\"player.notFound\"}"}
2024/10/13 - 23:11:20.175       ERROR   initialize/gin.go:123   [Recovery from panic]   {"error": "invalid argument to Intn", "request": "POST /api/event/post HTTP/1.1 Host: 127.0.0.1:19997 Accept: */* Accept-Encoding: gzip, deflate Accept-Language: * Connection: keep-alive Content-Length: 401 Content-Type: application/json Sec-Fetch-Mode: cors User-Agent: node X-Self-Id: 3771200484  "}
2024/10/13 - 23:11:20.176       ERROR   initialize/gin.go:133   goroutine 286 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
bfv-bot/common/initialize.Routers.GinRecovery.func2.1()
        /Users/nil/bfv-bot/common/initialize/gin.go:132 +0x3c9
panic({0x171ed00?, 0x19afe90?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
golang.org/x/exp/rand.(*Rand).Intn(...)
        /root/go/pkg/mod/golang.org/x/exp@v0.0.0-20230905200255-921286631fa9/rand/rand.go:134
golang.org/x/exp/rand.Intn(...)
        /root/go/pkg/mod/golang.org/x/exp@v0.0.0-20230905200255-921286631fa9/rand/rand.go:293
bfv-bot/common/utils.RandomInt(0x0)
        /Users/nil/bfv-bot/common/utils/random.go:10 +0x9e
bfv-bot/common/utils.draw(0xc00088dcf0, {0xc00088dca0, 0xd}, 0x0, 0xffffffffffffffff)
        /Users/nil/bfv-bot/common/utils/bfv.go:56 +0x425
bfv-bot/common/utils.QueryAndStore({0xc00050e0d3?, 0xa?})
        /Users/nil/bfv-bot/common/utils/bfv.go:632 +0x4a5
bfv-bot/api.cx(0x1757ea0?, 0xc000782000, {0xc00050e0d0?, 0x2?})
        /Users/nil/bfv-bot/api/event.go:558 +0x65
bfv-bot/api.shortCommandFunction(0xc000508000, 0xc000782000, {0xc00050e094, 0x2})
        /Users/nil/bfv-bot/api/event.go:634 +0xbb
bfv-bot/api.(*EventApi).Post(0x185a22d?, 0xc000782000)
        /Users/nil/bfv-bot/api/event.go:131 +0x65b
github.com/gin-gonic/gin.(*Context).Next(0xc000782000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 +0x2b
bfv-bot/common/initialize.Routers.Options.func3(0xc000782000)
        /Users/nil/bfv-bot/common/utils/gin.go:17 +0xb3
github.com/gin-gonic/gin.(*Context).Next(0xc000782000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 +0x2b
bfv-bot/common/initialize.Routers.GinRecovery.func2(0xc00078d840?)
        /Users/nil/bfv-bot/common/initialize/gin.go:139 +0x52
github.com/gin-gonic/gin.(*Context).Next(0xc000782000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 +0x2b
bfv-bot/common/initialize.Routers.GinLogger.func1(0xc000782000)
        /Users/nil/bfv-bot/common/initialize/gin.go:52 +0x225
github.com/gin-gonic/gin.(*Context).Next(...)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0004a0000, 0xc000782000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:489 +0x650
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0004a0000, {0x19b87c0, 0xc000142000}, 0xc0000b4d80)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:445 +0x198
net/http.serverHandler.ServeHTTP({0x19b6590?}, {0x19b87c0?, 0xc000142000?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc000364750, {0x19b9b08, 0xc0000140f0})
        /usr/local/go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3285 +0x4b4

2024/10/13 - 23:11:20.177       INFO    initialize/gin.go:60    [GIN] | 500 |   4428ms |        127.0.0.1 | POST     "/api/event/post"

**Comment by WONGIII** [comment]
放了

**Comment by WONGIII** [comment]
分辨率是1220x728，格式是png

**Comment by WONGIII** [comment]
server:
  # 机器人服务的端口, 后面配置napcat会用到
  port: 19997
  gin-mode: "release"
  # 战绩查询的背景图目录 图片长宽须是1220*728
  resource: "D:\ai\\qqbot\bfv-bot\bfv-bot\bfv-bot\\images"
  # 战绩查询的结果图目录
  output: "D:\ai\\qqbot\bfv-bot\bfv-bot\bfv-bot\test"
  # 战绩查询所需的字体
  font: "D:\ai\\qqbot\bfv-bot\bfv-bot\bfv-bot\bfv-font\\HarmonyOS_Sans_SC_Medium.ttf"
  # 数据库类型 支持mysql/sqlite
  db-type: "mysql"

**Comment by WONGIII** [comment]
2024/10/14 - 00:08:39.788       INFO    initialize/gin.go:60    [GIN] | 200 |      0ms |        127.0.0.1 | POST     "/api/event/post"
2024/10/14 - 00:08:40.003       DEBUG   utils/http.go:115       Get     {"url": "https://api.bfban.com/api/player", "stringResult": "{\"error\":1,\"code\":\"player.notFound\"}"}
2024/10/14 - 00:08:40.363       DEBUG   utils/bfv.go:57         {"图片数量": 1, "随机图片序号": 0}
2024/10/14 - 00:08:40.365       ERROR   utils/bfv.go:61 os.Open {"error": "open D:/ai/qqbot/bfv-bot/bfv-bot/bfv-bot/images/0.jpg: The system cannot find the file specified."}
2024/10/14 - 00:08:40.366       ERROR   api/event.go:560        utils.QueryAndStore     {"name": "wong1i1", "error": "背景图片打开失败"}
2024/10/14 - 00:08:40.368       INFO    initialize/gin.go:60    [GIN] | 200 |   3075ms |        127.0.0.1 | POST     "/api/event/post"

**Comment by WONGIII** [comment]
已解决，谢谢
