### ISSUE TITLE
程序增加黑名单功能  不能正常运行

### ISSUE THREAD

**Issue by 15h6** [fxxk-bot/bfv-bot#4]
### 出现问题的功能

addblack功能绑定不成功

### log文件夹内的日志
![Uploading 屏幕截图 2024-10-11 031239.png…]()

2024/10/11 - 03:09:31.395       [35mDEBUG[0m  initialize/gin.go:44    msg: {"self_id":2689691641,"user_id":1135432965,"time":1728587372,"message_id":1989468916,"message_seq":1989468916,"real_id":1989468916,"message_type":"group","sender":{"user_id":1135432965,"nickname":"星","card":"","role":"owner"},"raw_message":"addblack=guachengbaby  嘴臭","font":14,"sub_type":"normal","message":[{"type":"text","data":{"text":"addblack=guachengbaby  嘴臭"}}],"message_format":"array","post_type":"message","group_id":483143828}

2024/10/11 - 03:09:31.397       [31mERROR[0m  initialize/gin.go:123   [Recovery from panic]   {"error": "runtime error: invalid memory address or nil pointer dereference", "request": "POST /api/event/post HTTP/1.1 Host: 127.0.0.1:19997 Accept: */* Accept-Encoding: gzip, deflate Accept-Language: * Connection: keep-alive Content-Length: 448 Content-Type: application/json Sec-Fetch-Mode: cors User-Agent: node X-Self-Id: 2689691641  "}
2024/10/11 - 03:09:31.402       [31mERROR[0m  initialize/gin.go:133   goroutine 462 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
bfv-bot/common/initialize.Routers.GinRecovery.func2.1()
        /Users/nil/bfv-bot/common/initialize/gin.go:132 +0x3c9
panic({0xb04080?, 0x141fc70?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/feiin/sensitivewords.(*SensitiveWords).Find(0xaf7be0?, {0xc00009a280?, 0xc00009a2c0?})
        /root/go/pkg/mod/github.com/feiin/sensitivewords@v0.0.0-20231115031023-58bbe2fac957/sensitive_words.go:69 +0x13
bfv-bot/api.(*EventApi).Post(0xbfa047?, 0xc000290100)
        /Users/nil/bfv-bot/api/event.go:119 +0x4dd
github.com/gin-gonic/gin.(*Context).Next(0xc000290100)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 +0x2b
bfv-bot/common/initialize.Routers.Options.func3(0xc000290100)
        /Users/nil/bfv-bot/common/utils/gin.go:17 +0xb3
github.com/gin-gonic/gin.(*Context).Next(0xc000290100)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 +0x2b
bfv-bot/common/initialize.Routers.GinRecovery.func2(0xc0000d7840?)
        /Users/nil/bfv-bot/common/initialize/gin.go:139 +0x52
github.com/gin-gonic/gin.(*Context).Next(0xc000290100)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 +0x2b
bfv-bot/common/initialize.Routers.GinLogger.func1(0xc000290100)
        /Users/nil/bfv-bot/common/initialize/gin.go:52 +0x225
github.com/gin-gonic/gin.(*Context).Next(...)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000468340, 0xc000290100)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:489 +0x650
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000468340, {0xd58480, 0xc000166000}, 0xc000446000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:445 +0x198
net/http.serverHandler.ServeHTTP({0xd56208?}, {0xd58480?, 0xc000166000?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc0002ac090, {0xd597c8, 0xc0004a43c0})
        /usr/local/go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3285 +0x4b4

**Comment by 15h6** [comment]
程序增加服务器id不成功


![屏幕截图 2024-10-11 031950](https://github.com/user-attachments/assets/693bfae0-3ee5-4530-9bfe-d8f1cb44b221)



2024/10/11 - 03:19:20.112       [35mDEBUG[0m  initialize/gin.go:44    msg: {"self_id":2689691641,"user_id":1135432965,"time":1728587960,"message_id":616900484,"message_seq":616900484,"real_id":616900484,"message_type":"group","sender":{"user_id":1135432965,"nickname":"星","card":"","role":"owner"},"raw_message":"bindgameid=9570517060573","font":14,"sub_type":"normal","message":[{"type":"text","data":{"text":"bindgameid=9570517060573"}}],"message_format":"array","post_type":"message","group_id":483143828}

2024/10/11 - 03:19:20.114       [31mERROR[0m  initialize/gin.go:123   [Recovery from panic]   {"error": "runtime error: invalid memory address or nil pointer dereference", "request": "POST /api/event/post HTTP/1.1 Host: 127.0.0.1:19997 Accept: */* Accept-Encoding: gzip, deflate Accept-Language: * Connection: keep-alive Content-Length: 435 Content-Type: application/json Sec-Fetch-Mode: cors User-Agent: node X-Self-Id: 2689691641  "}
2024/10/11 - 03:19:20.126       [31mERROR[0m  initialize/gin.go:133   goroutine 1646 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
bfv-bot/common/initialize.Routers.GinRecovery.func2.1()
        /Users/nil/bfv-bot/common/initialize/gin.go:132 +0x3c9
panic({0xb04080?, 0x141fc70?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/feiin/sensitivewords.(*SensitiveWords).Find(0xaf7be0?, {0xc0000360a8?, 0xc0000360d8?})
        /root/go/pkg/mod/github.com/feiin/sensitivewords@v0.0.0-20231115031023-58bbe2fac957/sensitive_words.go:69 +0x13
bfv-bot/api.(*EventApi).Post(0xbfa047?, 0xc000298000)
        /Users/nil/bfv-bot/api/event.go:119 +0x4dd
github.com/gin-gonic/gin.(*Context).Next(0xc000298000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 +0x2b
bfv-bot/common/initialize.Routers.Options.func3(0xc000298000)
        /Users/nil/bfv-bot/common/utils/gin.go:17 +0xb3
github.com/gin-gonic/gin.(*Context).Next(0xc000298000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 +0x2b
bfv-bot/common/initialize.Routers.GinRecovery.func2(0xc000047840?)
        /Users/nil/bfv-bot/common/initialize/gin.go:139 +0x52
github.com/gin-gonic/gin.(*Context).Next(0xc000298000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 +0x2b
bfv-bot/common/initialize.Routers.GinLogger.func1(0xc000298000)
        /Users/nil/bfv-bot/common/initialize/gin.go:52 +0x225
github.com/gin-gonic/gin.(*Context).Next(...)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000468340, 0xc000298000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:489 +0x650
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000468340, {0xd58480, 0xc0001d4000}, 0xc000446000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:445 +0x198
net/http.serverHandler.ServeHTTP({0xd56208?}, {0xd58480?, 0xc0001d4000?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc0002ac000, {0xd597c8, 0xc0004a43c0})
        /usr/local/go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3285 +0x4b4

**Comment by 15h6** [comment]
同意加群后 无通知


![屏幕截图 2024-10-11 032746](https://github.com/user-attachments/assets/9792c676-f8b8-4773-9c7f-db22eb971259)

2024/10/11 - 03:31:39.572       [35mDEBUG[0m  initialize/gin.go:44    msg: {"time":1728588699,"self_id":2689691641,"post_type":"request","group_id":483143828,"user_id":2717138878,"request_type":"group","comment":"问题：本群的密码是？\n答案：guachengbaby","flag":"483143828|1728588699765458|7","sub_type":"add"}

2024/10/11 - 03:31:39.573       [34mINFO[0m   initialize/gin.go:60    [GIN] |[0;42m 200 [0m|      0ms |        127.0.0.1 |[0;48;2;120;220;232;38;2;255;255;255m POST    [0m "/api/event/post"
2024/10/11 - 03:31:39.729       [35mDEBUG[0m  initialize/gin.go:44    msg: {"time":1728588699,"self_id":2689691641,"post_type":"notice","group_id":483143828,"user_id":2717138878,"notice_type":"group_increase","operator_id":2689691641,"sub_type":"approve"}

2024/10/11 - 03:31:39.732       [34mINFO[0m   initialize/gin.go:60    [GIN] |[0;42m 200 [0m|      0ms |        127.0.0.1 |[0;48;2;120;220;232;38;2;255;255;255m POST    [0m "/api/event/post"
2024/10/11 - 03:31:41.466       [35mDEBUG[0m  utils/http.go:115       Get     {"url": "https://api.bfvrobot.net/api/v2/bfv/checkPlayer", "stringResult": "{\"status\":1,\"message\":\"successful\",\"data\":{\"personaId\":1003420276402,\"name\":\"guachengbaby\",\"userId\":1006559876402}}"}

**Comment by AgMahone** [comment]
服务器绑定功能我测试也存在问题，需要等待作者排查
黑名单添加需要与机器人私聊，并且命令格式为addblack=id，接下来机器人会回复一条消息让你输入原因。
加群修改名片使用文档明确标注，加群验证方式必须选择"需要回答问题并由管理员审核", 且问题必须为"游戏ID?(必须填写正确)"
![image](https://github.com/user-attachments/assets/92ff60ab-487f-49ae-b677-35a60bee06e0)

**Comment by 15h6** [comment]
私聊机器人 没有反应
![Uploading 屏幕截图 2024-10-11 095057.png…]()


2024/10/11 - 09:50:29.061       [35mDEBUG[0m  initialize/gin.go:44    msg: {"self_id":2689691641,"user_id":1135432965,"time":1728611424,"message_id":499566028,"message_seq":499566028,"real_id":499566028,"message_type":"private","sender":{"user_id":1135432965,"nickname":"星","card":""},"raw_message":"addblack=a263914641","font":14,"sub_type":"friend","message":[{"type":"text","data":{"text":"addblack=a263914641"}}],"message_format":"array","post_type":"message"}

2024/10/11 - 09:50:29.065       [34mINFO[0m   initialize/gin.go:60    [GIN] |[0;42m 200 [0m|      2ms |        127.0.0.1 |[0;48;2;120;220;232;38;2;255;255;255m POST    [0m "/api/event/post"

**Comment by 15h6** [comment]
![Screenshot_2024-10-11-10-11-09-55_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/user-attachments/assets/18144f48-1bad-45de-8c9b-1286e3d6c940)
这边是我的qq号，看了数据库有这个黑名单的记录，可以正常删除

**Comment by 15h6** [comment]
![Screenshot_2024-10-11-10-17-41-51_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/user-attachments/assets/795b10c5-c932-4c9e-9ea3-be113aa2aefc)
是这样的情况，不提示黑名单添加过程，

**Comment by 15h6** [comment]
debug:
2024/10/11 - 14:28:46.524	[35mDEBUG[0m	initialize/gin.go:44	msg: {"self_id":2689691641,"user_id":1135432965,"time":1728628125,"message_id":1697968250,"message_seq":1697968250,"real_id":1697968250,"message_type":"private","sender":{"user_id":1135432965,"nickname":"星","card":""},"raw_message":".help","font":14,"sub_type":"friend","message":[{"type":"text","data":{"text":".help"}}],"message_format":"array","post_type":"message"}

2024/10/11 - 14:28:51.298	[35mDEBUG[0m	initialize/gin.go:44	msg: {"self_id":2689691641,"user_id":1135432965,"time":1728628130,"message_id":2029073661,"message_seq":2029073661,"real_id":2029073661,"message_type":"private","sender":{"user_id":1135432965,"nickname":"星","card":""},"raw_message":"addblack=a263914641","font":14,"sub_type":"friend","message":[{"type":"text","data":{"text":"addblack=a263914641"}}],"message_format":"array","post_type":"message"}

2024/10/11 - 14:28:54.940	[35mDEBUG[0m	initialize/gin.go:44	msg: {"self_id":2689691641,"user_id":1135432965,"time":1728628133,"message_id":1563079226,"message_seq":1563079226,"real_id":1563079226,"message_type":"private","sender":{"user_id":1135432965,"nickname":"星","card":""},"raw_message":"1","font":14,"sub_type":"friend","message":[{"type":"text","data":{"text":"1"}}],"message_format":"array","post_type":"message"}

2024/10/11 - 14:28:55.453	[35mDEBUG[0m	utils/http.go:115	Get	{"url": "https://api.bfvrobot.net/api/v2/bfv/checkPlayer", "stringResult": "{\"status\":1,\"message\":\"successful\",\"data\":{\"personaId\":1003613357116,\"name\":\"a263914641\",\"userId\":1006854357116}}"}
2024/10/11 - 14:28:59.676	[35mDEBUG[0m	initialize/gin.go:44	msg: {"self_id":2689691641,"user_id":1135432965,"time":1728628138,"message_id":1463918665,"message_seq":1463918665,"real_id":1463918665,"message_type":"private","sender":{"user_id":1135432965,"nickname":"星","card":""},"raw_message":"moveblack=a263914641","font":14,"sub_type":"friend","message":[{"type":"text","data":{"text":"moveblack=a263914641"}}],"message_format":"array","post_type":"message"}




![屏幕截图 2024-10-11 143043](https://github.com/user-attachments/assets/ac99dd21-2ee0-4206-abbb-8d66d9cc7580)

info：
2024/10/11 - 14:28:46.526	[34mINFO[0m	initialize/gin.go:60	[GIN] |[0;42m 200 [0m|      0ms |        127.0.0.1 |[0;48;2;120;220;232;38;2;255;255;255m POST    [0m "/api/event/post"
2024/10/11 - 14:28:51.303	[34mINFO[0m	initialize/gin.go:60	[GIN] |[0;42m 200 [0m|      2ms |        127.0.0.1 |[0;48;2;120;220;232;38;2;255;255;255m POST    [0m "/api/event/post"
2024/10/11 - 14:28:55.457	[34mINFO[0m	initialize/gin.go:60	[GIN] |[0;42m 200 [0m|    514ms |        127.0.0.1 |[0;48;2;120;220;232;38;2;255;255;255m POST    [0m "/api/event/post"
2024/10/11 - 14:28:59.677	[34mINFO[0m	initialize/gin.go:60	[GIN] |[0;42m 200 [0m|      0ms |        127.0.0.1 |[0;48;2;120;220;232;38;2;255;255;255m POST    [0m "/api/event/post"

**Comment by 15h6** [comment]
我可以说没有吗

**Comment by 15h6** [comment]
是不是我接口设置的有问题 我之前设置服务器开启成功会通知绑定的管理员，现在设置半天一直没有
![Uploading 屏幕截图 2024-10-11 144553.png…]()

**Comment by 15h6** [comment]
佬 有没有详细的机器人napcat配置 我已经弄了好几天了 接口我也试了好多

**Comment by 15h6** [comment]
我只改了机器人配置里的address地址   还有napcat里面的port和posturls.就是上面的图片

**Comment by 15h6** [comment]
![Uploading Image_1728631234098.png…]()

**Comment by 15h6** [comment]
群聊发送服务器名  机器人不能正常回复服务器信息

2024/10/12 - 16:52:40.729       [34mINFO[0m   initialize/gin.go:60    [GIN] |[0;41m 500 [0m|      8ms |        127.0.0.1 |[0;48;2;120;220;232;38;2;255;255;255m POST    [0m "/api/event/post"
2024/10/12 - 16:52:50.480       [35mDEBUG[0m  initialize/gin.go:44    msg: {"self_id":3996023151,"user_id":1135432965,"time":1728723170,"message_id":1193403730,"real_id":1193403730,"message_seq":1193403730,"message_type":"group","sender":{"user_id":1135432965,"nickname":"星","card":"","role":"owner","title":""},"raw_message":"FS","font":14,"sub_type":"normal","message":[{"type":"text","data":{"text":"FS"}}],"message_format":"array","post_type":"message","group_id":984599806}

2024/10/12 - 16:52:50.483       [31mERROR[0m  initialize/gin.go:123   [Recovery from panic]   {"error": "runtime error: invalid memory address or nil pointer dereference", "request": "POST /api/event/post HTTP/1.1 Host: 127.0.0.1:15153 Accept: */* Accept-Encoding: gzip, deflate Accept-Language: * Connection: keep-alive Content-Length: 405 Content-Type: application/json Sec-Fetch-Mode: cors User-Agent: node X-Self-Id: 3996023151  "}
2024/10/12 - 16:52:50.488       [31mERROR[0m  initialize/gin.go:133   goroutine 658 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
bfv-bot/common/initialize.Routers.GinRecovery.func2.1()
        /Users/nil/bfv-bot/common/initialize/gin.go:132 +0x3c9
panic({0x10740e0?, 0x198fc70?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/feiin/sensitivewords.(*SensitiveWords).Find(0x1067c40?, {0xc0000a84be?, 0xc0000a856c?})
        /root/go/pkg/mod/github.com/feiin/sensitivewords@v0.0.0-20231115031023-58bbe2fac957/sensitive_words.go:69 +0x13
bfv-bot/api.(*EventApi).Post(0x116a0c7?, 0xc0003d2000)
        /Users/nil/bfv-bot/api/event.go:119 +0x4dd
github.com/gin-gonic/gin.(*Context).Next(0xc0003d2000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 +0x2b
bfv-bot/common/initialize.Routers.Options.func3(0xc0003d2000)
        /Users/nil/bfv-bot/common/utils/gin.go:17 +0xb3
github.com/gin-gonic/gin.(*Context).Next(0xc0003d2000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 +0x2b
bfv-bot/common/initialize.Routers.GinRecovery.func2(0xc000485840?)
        /Users/nil/bfv-bot/common/initialize/gin.go:139 +0x52
github.com/gin-gonic/gin.(*Context).Next(0xc0003d2000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 +0x2b
bfv-bot/common/initialize.Routers.GinLogger.func1(0xc0003d2000)
        /Users/nil/bfv-bot/common/initialize/gin.go:52 +0x225
github.com/gin-gonic/gin.(*Context).Next(...)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0001484e0, 0xc0003d2000)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:489 +0x650
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0001484e0, {0x12c85e0, 0xc00039a000}, 0xc000450120)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:445 +0x198
net/http.serverHandler.ServeHTTP({0x12c6368?}, {0x12c85e0?, 0xc00039a000?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc0001a62d0, {0x12c9928, 0xc00044e3c0})
        /usr/local/go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3285 +0x4b4
