### ISSUE TITLE
机器人与服务器绑定问题

### ISSUE THREAD

**Issue by 15h6** [fxxk-bot/bfv-bot#5]
### 出现问题的功能

机器人是不可以增加多个管理员吗 我按照yaml语法添加 运行失败

* 'qq-bot.admin-qq' expected type 'int64', got unconvertible type '[]interface {}', value: '[11xxxxxx5 271xxxxx]'

goroutine 1 [running]:
bfv-bot/common/initialize.Viper()
        /Users/nil/bfv-bot/common/initialize/viper.go:24 +0x17c
main.main()

**Comment by 15h6** [comment]
那是否考虑支持几个发送黑名单/卡排队提醒的qq群功能

**Comment by 15h6** [comment]
出现问题的功能
网站开服每次的gameid都不一样，这意味着每次都要重新绑定，不知道有没有解决办法
![3bb77b37c34ed68325b30dec07ff4632](https://github.com/user-attachments/assets/085c60fb-7e0f-45d9-99a0-0f2f2c67e5db)




![98a4b090cf4058aa4a52718257729d44](https://github.com/user-attachments/assets/0716a6f0-e130-492e-95b7-6d246b4b4c45)

**Comment by 15h6** [comment]
给多个群发送群黑名单/卡排队提醒，有的群组人多群多，管理员不能一下子看到黑名单提示，不知道可以实现吗，果然太麻烦就算了

**Comment by 15h6** [comment]
给通知群加上就会报错
  admin-group: 
    - 170406853
    - 653927355
  # 启用机器人服务的群
  active-group:
    - 483143828
    - 170406853
    - 653927355
    - 984599806

qq-bot.admin-group' expected type 'int64', got unconvertible type '[]interface {}', value: '[170406853 653927355]'


goroutine 1 [running]:
bfv-bot/common/initialize.Viper()
        /Users/nil/bfv-bot/common/initialize/viper.go:24 +0x17c
main.main()
        /Users/nil/bfv-bot/main.go:17 +0x1f
