### ISSUE TITLE
机器人不能正常回复服务器信息

### ISSUE THREAD

**Issue by 15h6** [fxxk-bot/bfv-bot#7]
群聊发送服务器名 机器人不能正常回复服务器信息

2024/10/12 - 16:52:40.729 �[34mINFO�[0m initialize/gin.go:60 [GIN] |�[0;41m 500 �[0m| 8ms | 127.0.0.1 |�[0;48;2;120;220;232;38;2;255;255;255m POST �[0m "/api/event/post"
2024/10/12 - 16:52:50.480 �[35mDEBUG�[0m initialize/gin.go:44 msg: {"self_id":3996023151,"user_id":1135432965,"time":1728723170,"message_id":1193403730,"real_id":1193403730,"message_seq":1193403730,"message_type":"group","sender":{"user_id":1135432965,"nickname":"星","card":"","role":"owner","title":""},"raw_message":"FS","font":14,"sub_type":"normal","message":[{"type":"text","data":{"text":"FS"}}],"message_format":"array","post_type":"message","group_id":984599806}

2024/10/12 - 16:52:50.483 �[31mERROR�[0m initialize/gin.go:123 [Recovery from panic] {"error": "runtime error: invalid memory address or nil pointer dereference", "request": "POST /api/event/post HTTP/1.1 Host: 127.0.0.1:15153 Accept: / Accept-Encoding: gzip, deflate Accept-Language: * Connection: keep-alive Content-Length: 405 Content-Type: application/json Sec-Fetch-Mode: cors User-Agent: node X-Self-Id: 3996023151 "}
2024/10/12 - 16:52:50.488 �[31mERROR�[0m initialize/gin.go:133 goroutine 658 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
bfv-bot/common/initialize.Routers.GinRecovery.func2.1()
/Users/nil/bfv-bot/common/initialize/gin.go:132 +0x3c9
panic({0x10740e0?, 0x198fc70?})
/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/feiin/sensitivewords.(*SensitiveWords).Find(0x1067c40?, {0xc0000a84be?, 0xc0000a856c?})
/root/go/pkg/mod/github.com/feiin/sensitivewords@v0.0.0-20231115031023-58bbe2fac957/sensitive_words.go:69 +0x13
bfv-bot/api.(*EventApi).Post(0x116a0c7?, 0xc0003d2000)
/Users/nil/bfv-bot/api/event.go:119 +0x4dd
github.com/gin-gonic/gin.(*Context).Next(0xc0003d2000)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 +0x2b
bfv-bot/common/initialize.Routers.Options.func3(0xc0003d2000)
/Users/nil/bfv-bot/common/utils/gin.go:17 +0xb3
github.com/gin-gonic/gin.(*Context).Next(0xc0003d2000)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 +0x2b
bfv-bot/common/initialize.Routers.GinRecovery.func2(0xc000485840?)
/Users/nil/bfv-bot/common/initialize/gin.go:139 +0x52
github.com/gin-gonic/gin.(*Context).Next(0xc0003d2000)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 +0x2b
bfv-bot/common/initialize.Routers.GinLogger.func1(0xc0003d2000)
/Users/nil/bfv-bot/common/initialize/gin.go:52 +0x225
github.com/gin-gonic/gin.(*Context).Next(...)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0001484e0, 0xc0003d2000)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:489 +0x650
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0001484e0, {0x12c85e0, 0xc00039a000}, 0xc000450120)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:445 +0x198
net/http.serverHandler.ServeHTTP({0x12c6368?}, {0x12c85e0?, 0xc00039a000?}, 0x6?)
/usr/local/go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc0001a62d0, {0x12c9928, 0xc00044e3c0})
/usr/local/go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
/usr/local/go/src/net/http/server.go:3285 +0x4b4

**Comment by 15h6** [comment]
好的辛苦

**Comment by 15h6** [comment]
佬，可以把查询屏蔽指令改成pb吗，大部分都是这个

**Comment by 15h6** [comment]
好的

**Comment by 15h6** [comment]
好的 佬
